#!/bin/sh
#
# Build or run a docker image of freech
#

ACTION=${1:-run}
MODE=${2:---local}

IMAGE_NAME=freech
REMOTE_IMAGE_NAME=martkist/freech

set -e

shift

case $ACTION in

build)
  echo Building $IMAGE_NAME
  docker build -t $IMAGE_NAME .
  ;;

run)
  if [ "$MODE" = "--remote" ]; then
    shift
    IMAGE_NAME=$REMOTE_IMAGE_NAME
    echo Pulling new version of $IMAGE_NAME
    docker pull $IMAGE_NAME
  fi
  echo Running $IMAGE_NAME
  docker run -d -p 28332:28332 -v $HOME/.freech:/root/.freech $IMAGE_NAME "$@"
  echo "Freech should now be running at http://localhost:28332 (access with \"user\" / \"pwd\")"
  ;;

stop)
  CID=$(docker ps | grep freech | awk '{print $1}')
  if [ "$CID" ]; then
    echo Stopping container $CID
    docker stop $CID
    docker rm $CID
  fi
  ;;

*)
  echo Usage:
  echo "         $0 run [ARGS FOR FREECHD..]"
  echo "         Run freech from a local docker build (default)"
  echo
  echo "         $0 run --remote [ARGS FOR FREECHD..]"
  echo "         Run freech from the remote docker build at \"$REMOTE_IMAGE_NAME\""
  echo
  echo "         $0 build"
  echo "         Build a local docker image for freech"

  exit 2

esac
