#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

export FREECH_CORE_PATH='/home/vagrant/freech-core'
export FREECH_HOME='/home/vagrant/.freech'

alias freechd='$FREECH_CORE_PATH/freechd'



if [ ! -n "$FREECH_OLD_PATH" ]; then
	echo 'setting up the environment'
	export FREECH_OLD_PATH=$PATH
	export FREECH_OLD_PS1=$PS1
	export PATH=$DIR/bin:$PATH
	export PS1="(freech)$PS1\n> "
else
	echo 'already active'
fi

function deactivate {
	if [ -n "$FREECH_OLD_PATH" ]; then
		echo 'cleaning up the environment'
		export PATH=$FREECH_OLD_PATH
		export PS1=$FREECH_OLD_PS1
		unset FREECH_OLD_PATH
		unset FREECH_OLD_PS1
		unset -f deactivate
	fi
}